baseURL = 'https://czyrnik.me'
languageCode = 'en-us'
title = 'Tonis Blog'
theme = "anubis"

[author]
name = "Toni Czyrnik"

[params]
author = "Toni Czyrnik"
description = "Personal Blog"
dateFormat = "01.01.2022"
paginationSinglePost = true
style = "auto"
readMore = false

# utteranc.es support
utterancesRepo = ""  # mandatory
utterancesTheme = "" # optional
utterancesIssue = "" # optional
utterancesLabel = "" # optional


[[params.social]]
id = "linkedin"
url = "https://www.linkedin.com/in/czyrnik/"

[[params.social]]
id = "github"
url = "https://github.com/ToniCzyrnik/ToniCzyrnik.github.io"

[[params.social]]
id = "email"
url = "mailto:mail@czyrnik.me"


[menu]

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 1

[markup.goldmark.renderer]
unsafe = true
