baseURL = 'https://czyrnik.me'
languageCode = 'en-us'
title = "Toni's Blog"
theme = "anubis"

[author]
name = "Toni Czyrnik"

[params]
author = "Toni Czyrnik"
description = "Personal Blog"
dateFormat = "02 Jan 2006"
paginationSinglePost = true
style = "auto"
readMore = false

# utteranc.es support
utterancesRepo = ""  # mandatory
utterancesTheme = "" # optional
utterancesIssue = "" # optional
utterancesLabel = "" # optional


[[params.social]]
id = "linkedin"
url = "https://www.linkedin.com/in/czyrnik/"

[[params.social]]
id = "github"
url = "https://github.com/ToniCzyrnik/ToniCzyrnik.github.io"

[[params.social]]
id = "email"
url = "mailto:mail@czyrnik.me"


[menu]

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 1

[[menu.main]]
identifier = "newsletter"
name = "Newsletter"
url = "/newsletter/"
weight = 2

[markup.goldmark.renderer]
unsafe = true
